services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    env_file:
      - ./.env
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: cards_backend
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./backend:/backend/

  frontend:
    build: ./frontend
    container_name: cards_frontend
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend/
      - /frontend/node_modules

  nginx:
    build: ./nginx
    container_name: cards_nginx
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - backend

volumes:
  db_data:
