services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    env_file:
      - ./.env

  backend:
    build: ./backend
    container_name: cards_backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: cards_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    build: ./nginx
    container_name: cards_nginx
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend